import streamlit as st
import pandas as pd
import numpy as np
from computation.traverse import compute_lat_depart, bowditch_adjustment_with_steps
from utils.plot_traverse import plot_traverse
from exports.pdf_export import export_pdf

st.set_page_config(layout="wide", page_title="Survey Computation Audit")

st.title("📐 Survey Computation & Audit Tool")

# Sidebar
st.sidebar.header("🛠️ Settings")
start_x = st.sidebar.number_input("Starting Easting (X)", value=0.0, format="%.3f")
start_y = st.sidebar.number_input("Starting Northing (Y)", value=0.0, format="%.3f")

file = st.file_uploader("Upload Survey File", type=["xlsx", "csv"])

if file:
    # Read the file
    df_raw = pd.read_csv(file) if file.name.endswith('.csv') else pd.read_excel(file)
    
    if df_raw is not None:
        # Step 1: Process numeric columns
        df_lat_dep = compute_lat_depart(df_raw)
        
        # Validation Check: Is there data?
        if df_lat_dep['Distance'].sum() == 0:
            st.error("❌ Error: All Distances are zero. Please check that your file has a column named 'Distance' or 'Length' with numeric values.")
        else:
            # Step 2: Recalculate everything
            df_final, mis_n, mis_e, total_dist = bowditch_adjustment_with_steps(df_lat_dep, start_x, start_y)
            
            # Summary Metrics
            st.success("### ✅ Audit Summary")
            col1, col2, col3 = st.columns(3)
            col1.metric("Total Distance", f"{total_dist:.3f} m")
            col2.metric("Linear Misclosure", f"{np.sqrt(mis_n**2 + mis_e**2):.4f} m")
            col3.metric("Precision", f"1 : {int(total_dist/np.sqrt(mis_n**2 + mis_e**2)) if mis_n != 0 else 0}")

            # Audit Tabs
            tab1, tab2 = st.tabs(["🗺️ Plot", "📚 Full Mathematical Audit"])
            
            with tab1:
                st.pyplot(plot_traverse(df_final))
            
            with tab2:
                st.subheader("1. Calculations for Changes (ΔN and ΔE)")
                st.write("Verification of Trigonometry (Distance × Cos/Sin):")
                st.table(df_final[['code', 'Math_Lat', 'Math_Dep']])

                st.subheader("2. Adjustment Calculations")
                st.write("Bowditch Corrections applied to each line:")
                st.table(df_final[['code', 'Corr_Lat', 'Corr_Dep']])

                st.subheader("3. Coordinate Accumulation")
                st.write("Final result reached by adding adjusted changes to previous coordinates:")
                c1, c2 = st.columns(2)
                c1.table(df_final[['code', 'Math_N', 'Final_N']])
                c2.table(df_final[['code', 'Math_E', 'Final_E']])

            # Export
            pdf_btn = export_pdf(df_final, mis_n, mis_e, 0, "", "", "Report Generated by Audit Tool")
            st.download_button("📥 Download Audit PDF", pdf_btn, "Survey_Audit.pdf")
